version: "3.7"

services:
  fhir:
    container_name: hapifhir
    image: hapiproject/hapi:v5.1.0
    networks:
      - fhir-benchmark
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./application.yml:/data/hapi/application.yml
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/fhir?currentSchema=public"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQL10Dialect
      HAPI_FHIR_SERVER_ADDRESS: "http://localhost:8080/fhir"
      VALIDATION_REQUESTS_ENABLED: "false"
      
    depends_on:
      - db

  db:
    container_name: hapidb
    image: postgres:12.4-alpine
    restart: always
    networks:
      - fhir-benchmark
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir

volumes:
  hapi-data: {}

networks:
  fhir-benchmark:
    external: true
    name: fhir-benchmark