version: '3.7'
services:
  blaze:
    container_name: blaze
    image: "samply/blaze:0.11.0-alpha.2"
    environment:
      BASE_URL: "http://localhost:8081"
      JAVA_TOOL_OPTIONS: "-Xmx4g"
      LOG_LEVEL: debug
    ports:
    - "8081:8080"
    volumes:
    - "blaze-data:/app/data"
    networks:
      - fhir-benchmark

volumes:
  blaze-data:

networks:
  fhir-benchmark:
    external: true
    name: fhir-benchmark
